/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Roles available at registration: `candidate`, `hr`, `manager`, `recruiter`.
         *     The `administrator` role is created manually via DB or a seed script.
         *     `tenant_id` is not sent by the client — the singleton TENANT_ID is injected (hidden multi-tenancy).
         *     Requires separated `consent` (RK §1.4): `account_processing` must be true;
         *     `talent_pool` / `cross_border` optional (empty by default). Extra fields (e.g. `iin`) are rejected.
         *     On success, sets HttpOnly access/refresh cookies + a readable CSRF cookie.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (email/password) → cookie session */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (cookie or Bearer + refresh cookie/body)
         * @description Access cookie or `Authorization: Bearer` authorizes the request.
         *     When using an access cookie, the `X-CSRF-Token` header is required (double-submit).
         *     Refresh is taken from the HttpOnly cookie or an optional body; hard-revoked in the token store.
         *     Cookies are cleared.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user (cookie or Bearer)
         * @description Includes `legal_acceptance_required`, `consent_refresh_required`, and
         *     `current_legal_policy_version` for the policy-update gate (RK).
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Universal auth — whether email already has an account */
        post: operations["checkEmailRegistered"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-legal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept current Terms + PD policy version (and refresh consent if expired) */
        post: operations["acceptLegalDocuments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate access/refresh (cookie or body refresh) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current consent grants for the authenticated user */
        get: operations["getConsent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update optional / required consent grants */
        patch: operations["updateConsent"];
        trace?: never;
    };
    "/auth/forget-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw consents and anonymize auth identity (GDPR Art.17 / RK §3.3) */
        post: operations["forgetMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Google/LinkedIn OAuth with consent snapshot
         * @description Requires separated consent (same as register). Stores consent with OAuth state,
         *     then redirects to the IdP authorize URL.
         */
        post: operations["oauthStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback → HireRank cookie session */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback/linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LinkedIn OAuth callback → HireRank cookie session */
        get: operations["linkedinCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own profile */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        /**
         * Delete own account
         * @description Administrators cannot delete themselves.
         */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        /** Update own profile */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change own password */
        patch: operations["changeMyPassword"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant users
         * @description Requires `users.manage` (administrator).
         *     Offset pagination via `skip` / `limit` (backend UsersPublic).
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create user (administrator)
         * @description Requires `users.manage`. `tenant_id` is always `settings.TENANT_ID`.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get user by ID
         * @description Self or administrator.
         */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /**
         * Delete user (administrator)
         * @description Requires `users.manage`. Cannot delete self.
         */
        delete: operations["deleteUserById"];
        options?: never;
        head?: never;
        /**
         * Update user (administrator)
         * @description Requires `users.manage`.
         */
        patch: operations["updateUserById"];
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant candidates
         * @description Available to: **administrator**, **hr**, **manager**.
         *
         *     Sorted by `created_at` (newest first). Decision product artifact — Automation options /
         *     Outcomes in Memory ([MEMORY.md](../../MEMORY.md)), not ai_score.
         *
         *     Manager sees only candidates assigned to vacancies, plus pending HITL for their tenant.
         */
        get: operations["listCandidates"];
        put?: never;
        /**
         * Create candidate card from JSON questionnaire
         * @description Used by **hr** to manually create a candidate from a personnel questionnaire JSON.
         *     After creation the candidate enters the tenant pool with status `unassigned`.
         *     Publishes `resume.uploaded` for Automation; notifications are created. Auto-ranking/score is not started.
         */
        post: operations["createCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Candidate card
         * @description Candidate sees only their own card.
         *     HR Operator, Manager, Administrator see any candidate in their tenant.
         */
        get: operations["getCandidateById"];
        put?: never;
        post?: never;
        /**
         * Delete candidate
         * @description Available only to **administrator**.
         */
        delete: operations["deleteCandidate"];
        options?: never;
        head?: never;
        /**
         * Update candidate card
         * @description Candidate may update their questionnaire until assignment / action_applied.
         *     HR Operator may edit any card.
         *     After a substantial update, a repeat `resume.uploaded` may be published for Automation.
         */
        patch: operations["updateCandidate"];
        trace?: never;
    };
    "/candidates/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign candidate to vacancy
         * @description Available only to **administrator** (manual path UC-04).
         *     MCP / HITL accept path is deferred (see `docs/openapi/future/` + UC-08).
         *
         *     After assignment the candidate status becomes `assigned`.
         */
        post: operations["assignCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/questionnaire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get candidate questionnaire */
        get: operations["getQuestionnaire"];
        /**
         * Fill or update candidate JSON questionnaire
         * @description Candidate submits the personnel questionnaire JSON form from the frontend.
         *     On first fill — the candidate enters the `unassigned` pool
         *     and `resume.uploaded` is published for Automation.
         */
        put: operations["updateQuestionnaire"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/resume-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Presigned / opaque resume URL (RLS-gated)
         * @description Loads the candidate under the RLS session first.
         *     Invisible / foreign IDs return **404**. Then returns a stub short-lived URL
         *     (real S3 deferred).
         */
        get: operations["getCandidateResumeUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant vacancies
         * @description Available to all authenticated tenant users.
         *     Manager and HR Operator see only vacancies for their `tenant_id`.
         */
        get: operations["listVacancies"];
        put?: never;
        /**
         * Create vacancy
         * @description Available only to **administrator**.
         */
        post: operations["createVacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Vacancy card
         * @description Available to all authenticated tenant users.
         *     Tenant isolation enforced by `tenant_id`.
         */
        get: operations["getVacancyById"];
        put?: never;
        post?: never;
        /**
         * Delete vacancy
         * @description Available only to **administrator**.
         */
        delete: operations["deleteVacancy"];
        options?: never;
        head?: never;
        /**
         * Update vacancy
         * @description Available only to **administrator**.
         */
        patch: operations["updateVacancy"];
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home dashboard — payload depends on user role
         * @description Single endpoint; response shape depends on `role` in JWT:
         *
         *     | Role | Response type |
         *     |------|-----------|
         *     | `administrator` | `AdminDashboard` |
         *     | `hr` | `HRDashboard` |
         *     | `manager` | `ManagerDashboard` |
         *     | `candidate` | `CandidateDashboard` |
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Separated consents (RK §1.4). Defaults must be false / empty — never pre-ticked. */
        ConsentGrant: {
            /**
             * @description Required — process PD for HireRank account
             * @example true
             */
            account_processing: boolean;
            /**
             * @description Optional — keep PD in talent pool / reserve
             * @example false
             */
            talent_pool: boolean;
            /**
             * @description Optional — cross-border transfer
             * @example false
             */
            cross_border: boolean;
            /**
             * @description Required non-empty when cross_border is true
             * @example []
             */
            cross_border_countries?: string[];
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example ivan@mrxcompany.kz
             */
            email: string;
            /**
             * Format: password
             * @example Str0ngPass!
             */
            password: string;
            /**
             * @description Administrator is created manually via seed / admin tooling.
             *     `tenant_id` is not sent — Core injects the singleton TENANT_ID from env.
             * @example hr
             * @enum {string}
             */
            role: "candidate" | "hr" | "manager" | "recruiter";
            /** @example Ivan */
            first_name?: string;
            /** @example Petrov */
            last_name?: string;
            consent: components["schemas"]["ConsentGrant"];
        };
        /**
         * @description Browser cookie session metadata. Access/refresh JWTs are delivered only via
         *     HttpOnly Set-Cookie — not in the JSON body.
         */
        AuthSession: {
            /**
             * @example cookie
             * @enum {string}
             */
            token_type: "cookie";
            /**
             * @description Access cookie TTL in seconds
             * @example 3600
             */
            expires_in: number;
        };
        ValidationError: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example Request validation failed */
            message: string;
            errors: {
                /** @example email */
                field: string;
                /** @example Must be a valid email address */
                message: string;
            }[];
        };
        ErrorResponse: {
            /** @example NOT_FOUND */
            code: string;
            /** @example Resource not found */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            /**
             * Format: email
             * @example ivan@mrxcompany.kz
             */
            email: string;
            /**
             * Format: password
             * @example Str0ngPass!
             */
            password: string;
        };
        RefreshRequest: {
            /**
             * @description Optional when refresh HttpOnly cookie is present
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token?: string;
        };
        /**
         * @example hr
         * @enum {string}
         */
        UserRole: "administrator" | "hr" | "manager" | "recruiter" | "candidate";
        User: {
            /**
             * Format: uuid
             * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
             */
            id: string;
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            tenant_id: string;
            /**
             * Format: email
             * @example ivan@mrxcompany.kz
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /** @example Ivan */
            first_name?: string | null;
            /** @example Petrov */
            last_name?: string | null;
            /** @example true */
            is_active: boolean;
            /**
             * Format: date-time
             * @example 2025-06-01T10:00:00Z
             */
            created_at?: string | null;
            /** @example 2026-08-06 */
            legal_policy_version?: string | null;
            /** Format: date-time */
            legal_accepted_at?: string | null;
            /** @description True when accepted policy version ≠ current LEGAL_POLICY_VERSION */
            legal_acceptance_required?: boolean;
            /** @description True when account_processing consent missing or expired */
            consent_refresh_required?: boolean;
            /** @example 2026-08-06 */
            current_legal_policy_version?: string;
        };
        ConsentPublic: components["schemas"]["ConsentGrant"];
        OAuthStartRequest: {
            consent: components["schemas"]["ConsentGrant"];
        };
        Message: {
            /** @example Password updated successfully */
            message: string;
        };
        /** @description PATCH /users/me body (UserUpdateMe) */
        UpdateUserRequest: {
            first_name?: string | null;
            last_name?: string | null;
            /** Format: email */
            email?: string;
        };
        /** @description PATCH /users/me/password (UpdatePassword) */
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        /** @description GET /users/ response (skip/limit pagination) */
        UsersPublic: {
            data: components["schemas"]["User"][];
            /** @example 42 */
            count: number;
        };
        /** @description POST /users/ (administrator). tenant_id is ignored / forced server-side. */
        CreateUserRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password?: string | null;
            role: components["schemas"]["UserRole"];
            first_name?: string | null;
            last_name?: string | null;
            /** @default true */
            is_active: boolean;
        };
        /** @description PATCH /users/{id} (UserUpdate) */
        AdminUpdateUserRequest: {
            /** Format: email */
            email?: string;
            /** Format: password */
            password?: string;
            is_active?: boolean;
            role?: components["schemas"]["UserRole"];
            first_name?: string | null;
            last_name?: string | null;
        };
        /**
         * @example unassigned
         * @enum {string}
         */
        CandidateStatus: "unassigned" | "assigned" | "pending_hitl" | "action_applied";
        /** @description One row from the LPK educational institutions table (item 7) */
        EducationEntry: {
            /**
             * @description Educational institution name and location
             * @example Al-Farabi Kazakh National University, Almaty
             */
            institution?: string;
            /**
             * @description Year of admission (string — form does not guarantee a number)
             * @example 2012
             */
            year_from?: string;
            /**
             * @description Year of graduation or departure
             * @example 2016
             */
            year_to?: string;
            /**
             * @description Year/course left (if did not graduate)
             * @example null
             */
            dropped_at_year?: string | null;
            /**
             * @description Specialty studied
             * @example Information Systems
             */
            specialty?: string;
            /**
             * @description Qualification and diploma / certificate number
             * @example Bachelor's diploma No. 012345
             */
            diploma?: string;
        };
        /**
         * @description Candidate personnel questionnaire — structure matches the official
         *     Personal Personnel Record Sheet (LPK, form lpk.html).
         *     Fields are numbered according to the form items.
         */
        Questionnaire: {
            /**
             * @description item 1 — Surname (form name=surname)
             * @example Seitkali
             */
            surname?: string;
            /**
             * @description item 1 — First name (form name=first_name)
             * @example Alibek
             */
            first_name?: string;
            /**
             * @description item 1 — Patronymic (form name=patronymic)
             * @example Serikovich
             */
            patronymic?: string;
            /**
             * @description item 2 — Gender (free-text from form)
             * @example male
             */
            gender?: string;
            /**
             * @description item 3 — Year, day and month of birth.
             *     Accepted as string: form is free-text; backend normalizes.
             * @example 1995-03-15
             */
            birth_date?: string;
            /**
             * @description item 4 — Place of birth (village/city, district, region, republic)
             * @example Almaty, Almaty Region, Kazakhstan
             */
            birth_place?: string;
            /**
             * @description item 5 — Nationality (form name=nationality)
             * @example Kazakh
             */
            nationality?: string;
            /**
             * @description item 6 — Citizenship (form name=citizenship)
             * @example Kazakhstan
             */
            citizenship?: string;
            /**
             * @description item 7 — Education level (free-text from form)
             * @example higher
             */
            education_level?: string;
            /** @description item 7 — Educational institutions table (up to 4 rows in form) */
            education?: components["schemas"]["EducationEntry"][];
            /**
             * @description item 8 — Native language and other languages, proficiency (free-text).
             *     Form has a single field name=languages.
             * @example Kazakh (native), Russian (fluent), English (read and translate with a dictionary)
             */
            languages?: string;
            /**
             * @description item 9 — Academic degree / academic title
             * @example
             */
            academic_degree?: string;
            /**
             * @description item 10 — Scientific works and inventions (two rows in form)
             * @example [
             *       "",
             *       ""
             *     ]
             */
            scientific_works?: string[];
        };
        Candidate: {
            /**
             * Format: uuid
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * Format: uuid
             * @description Linked User (if the candidate registered themselves)
             */
            user_id?: string | null;
            status: components["schemas"]["CandidateStatus"];
            /** Format: email */
            email?: string | null;
            /** @description Opaque object key or URL (presign via resume-url) */
            resume_url?: string | null;
            /** Format: uuid */
            assigned_vacancy_id?: string | null;
            questionnaire?: components["schemas"]["Questionnaire"];
            /**
             * Format: uuid
             * @description Pending or latest Automation decision package (when automation ships)
             */
            active_package_id?: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            total_pages: number;
        };
        PagedCandidateResponse: {
            items: components["schemas"]["Candidate"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description Used by HR Operator to manually create a candidate card */
        CreateCandidateRequest: {
            questionnaire: components["schemas"]["Questionnaire"];
            /** Format: email */
            email?: string | null;
            resume_url?: string | null;
        };
        UpdateQuestionnaireRequest: {
            questionnaire: components["schemas"]["Questionnaire"];
        };
        AssignCandidateRequest: {
            /**
             * Format: uuid
             * @example b2c3d4e5-f6a7-8901-bcde-f23456789012
             */
            vacancy_id: string;
        };
        ResumeUrlResponse: {
            /**
             * @description Short-lived opaque/presigned URL (stub until real S3)
             * @example https://presign.local/candidates/a1b2/resume?exp=900
             */
            url: string;
            /**
             * @description Seconds until URL expires
             * @example 900
             */
            expires_in: number;
        };
        /**
         * @example open
         * @enum {string}
         */
        VacancyStatus: "open" | "closed" | "draft";
        PipelineStage: {
            /** Format: uuid */
            id: string;
            /** @example Applied */
            stage_name: string;
            /** @example 0 */
            sort_order: number;
        };
        Vacancy: {
            /**
             * Format: uuid
             * @example b2c3d4e5-f6a7-8901-bcde-f23456789012
             */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example Backend Developer */
            title: string;
            /** @example Engineering */
            department?: string | null;
            /**
             * @example Looking for an experienced Backend developer to work on core services.
             *     Requirements: Python 3.10+, FastAPI, PostgreSQL.
             */
            description?: string | null;
            /**
             * @example [
             *       "Python",
             *       "FastAPI",
             *       "PostgreSQL",
             *       "3+ years experience"
             *     ]
             */
            requirements?: string[];
            status: components["schemas"]["VacancyStatus"];
            assigned_candidate_ids?: string[];
            /** @description Default pipeline on create — Applied, Screen, Interview, Offer */
            stages?: components["schemas"]["PipelineStage"][];
            /**
             * Format: uuid
             * @description id of the Administrator who created the vacancy
             */
            created_by: string;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        PagedVacancyResponse: {
            items: components["schemas"]["Vacancy"][];
            pagination: components["schemas"]["Pagination"];
        };
        CreateVacancyRequest: {
            /** @example Backend Developer */
            title: string;
            /** @example Engineering */
            department?: string | null;
            description?: string | null;
            requirements?: string[];
            /** @default draft */
            status: components["schemas"]["VacancyStatus"];
        };
        UpdateVacancyRequest: {
            title?: string;
            department?: string | null;
            description?: string | null;
            requirements?: string[];
            status?: components["schemas"]["VacancyStatus"];
        };
        AdminDashboard: {
            /** @example 34 */
            total_candidates?: number;
            /** @example 12 */
            unassigned_candidates?: number;
            /**
             * @description Candidates / packages awaiting Telegram HITL
             * @example 4
             */
            pending_hitl?: number;
            /** @example 8 */
            total_vacancies?: number;
            /** @example 5 */
            open_vacancies?: number;
            /** @example 15 */
            total_users?: number;
            /** @example 3 */
            unread_notifications?: number;
            /** @description Recent pending Automation packages (not rank-score) */
            recent_pending_packages?: {
                /** Format: uuid */
                package_id?: string;
                /** Format: uuid */
                candidate_id?: string;
                /** @example Alibek Seitkali */
                full_name?: string;
                /** @example 3 */
                scenario_count?: number;
            }[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "AdminDashboard";
        };
        HRDashboard: {
            /** @example 7 */
            candidates_created_by_me?: number;
            /** @example 34 */
            total_candidates?: number;
            /** @example 5 */
            open_vacancies?: number;
            /** @example 2 */
            unread_notifications?: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "HRDashboard";
        };
        ManagerDashboard: {
            /** @example 4 */
            assigned_candidates?: number;
            /** @example 2 */
            pending_hitl?: number;
            /** @example 5 */
            open_vacancies?: number;
            /** @example 1 */
            unread_notifications?: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "ManagerDashboard";
        };
        CandidateDashboard: {
            /** @example true */
            questionnaire_filled?: boolean;
            /**
             * @example unassigned
             * @enum {string}
             */
            status?: "unassigned" | "assigned" | "pending_hitl" | "action_applied";
            assigned_vacancy?: {
                /** Format: uuid */
                id?: string;
                /** @example Backend Developer */
                title?: string;
            } | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "CandidateDashboard";
        };
        DashboardResponse: components["schemas"]["AdminDashboard"] | components["schemas"]["HRDashboard"] | components["schemas"]["ManagerDashboard"] | components["schemas"]["CandidateDashboard"];
        /**
         * @description Legacy / Swagger form login (`POST /login/access-token`) for non-browser
         *     clients. Prefer cookie session via `/auth/login` for SPA/SSR.
         */
        TokenPair: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refresh_token: string;
            /**
             * @example bearer
             * @enum {string}
             */
            token_type: "bearer";
            /**
             * @description Access token TTL in seconds
             * @example 3600
             */
            expires_in?: number;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Not authenticated"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created; session in cookies */
            201: {
                headers: {
                    /** @description access_token (HttpOnly), refresh_token (HttpOnly), csrf_token */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_ALREADY_EXISTS",
                     *       "message": "This email is already registered"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful; JWTs only in Set-Cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_CREDENTIALS",
                     *       "message": "Email or password is incorrect"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Access blacklisted, refresh revoked, cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description CSRF Token missing or invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    checkEmailRegistered: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Registration status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        registered: boolean;
                    };
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptLegalDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    consent?: components["schemas"]["ConsentGrant"];
                };
            };
        };
        responses: {
            /** @description Updated user public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Consent required when account processing expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description CSRF Token missing or invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New cookies issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Separated consent flags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentPublic"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated consent state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentPublic"];
                };
            };
            /** @description Invalid consent combination */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    forgetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consents revoked, identity anonymized, cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Administrators cannot self-erase via this endpoint */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "linkedin";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartRequest"];
            };
        };
        responses: {
            /** @description Redirect to IdP */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing account_processing consent or provider misconfigured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to FRONTEND_HOST/auth with session cookies */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid state / IdP failure / inactive user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    linkedinCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to FRONTEND_HOST/auth with session cookies */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid state / IdP failure / inactive user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Administrators cannot self-delete */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Incorrect password or OAuth-only account */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersPublic"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Email already exists */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Insufficient permissions or self-delete */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: components["schemas"]["CandidateStatus"];
                /** @description Filter by vacancy */
                vacancy_id?: string;
                /** @description Search by full name or job title */
                search?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated candidate list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCandidateResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCandidateRequest"];
            };
        };
        responses: {
            /** @description Candidate created; `resume.uploaded` queued for Automation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Questionnaire validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only hr or administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCandidateById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionnaireRequest"];
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignCandidateRequest"];
            };
        };
        responses: {
            /** @description Candidate assigned to vacancy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Only administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate or vacancy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate already assigned to this vacancy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getQuestionnaire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate questionnaire */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Questionnaire not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateQuestionnaire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionnaireRequest"];
            };
        };
        responses: {
            /** @description Questionnaire saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Access denied (not questionnaire owner or status does not allow) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCandidateResumeUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resume URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUrlResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Candidate not visible under current tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVacancies: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: components["schemas"]["VacancyStatus"];
                /** @description Search by title or department */
                search?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vacancy list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedVacancyResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVacancyRequest"];
            };
        };
        responses: {
            /** @description Vacancy created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVacancyById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vacancy found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            /** @description Vacancy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vacancy deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vacancy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete vacancy with assigned candidates */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "VACANCY_HAS_CANDIDATES",
                     *       "message": "Cannot delete vacancy with assigned candidates"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVacancyRequest"];
            };
        };
        responses: {
            /** @description Vacancy updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
            /** @description Only administrator */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vacancy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data for the current role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
