import { Job, DEFAULT_STAGES } from "./types";

export const initialJobs: Job[] = [
  {
    id: "j1",
    title: "Senior Frontend Developer",
    department: "Engineering",
    status: "Открыта",
    createdAt: "2026-05-12",
    location: "Алматы / Удалённо",
    employmentType: "Полная занятость",
    description:
      "Ищем сильного фронтенд-разработчика для развития продуктовой платформы. React, TypeScript, опыт с дизайн-системами будет плюсом. Команда — 6 инженеров, еженедельные релизы.",
    stages: DEFAULT_STAGES,
  },
  {
    id: "j2",
    title: "Product Manager",
    department: "Product",
    status: "Открыта",
    createdAt: "2026-05-20",
    location: "Астана",
    employmentType: "Полная занятость",
    description:
      "Продуктовый менеджер для B2B-направления. Нужен опыт работы с discovery-исследованиями и метриками активации.",
    stages: DEFAULT_STAGES,
  },
  {
    id: "j3",
    title: "UX/UI дизайнер",
    department: "Design",
    status: "На паузе",
    createdAt: "2026-04-02",
    location: "Удалённо",
    employmentType: "Полная занятость",
    description: "Дизайнер в продуктовую команду. Портфолио с кейсами по мобильным приложениям обязательно.",
    stages: DEFAULT_STAGES,
  },
  {
    id: "j4",
    title: "Backend Engineer (Go)",
    department: "Engineering",
    status: "Открыта",
    createdAt: "2026-06-01",
    location: "Алматы",
    employmentType: "Полная занятость",
    description: "Backend-разработчик на Go для платёжного сервиса. Высокие нагрузки, микросервисы, Kafka.",
    stages: DEFAULT_STAGES,
  },
  {
    id: "j5",
    title: "HR Business Partner",
    department: "HR",
    status: "Закрыта",
    createdAt: "2026-03-10",
    location: "Астана",
    employmentType: "Полная занятость",
    description: "HRBP для поддержки инженерных команд. Позиция закрыта в июне.",
    stages: DEFAULT_STAGES,
  },
  {
    id: "j6",
    title: "Sales Manager",
    department: "Sales",
    status: "Открыта",
    createdAt: "2026-06-15",
    location: "Алматы",
    employmentType: "Полная занятость",
    description: "Менеджер по продажам корпоративным клиентам. Опыл в B2B SaaS приветствуется.",
    stages: DEFAULT_STAGES,
  },
];
