import { Job, DEFAULT_STAGES } from "./types";

export const initialJobs: Job[] = [
  {
    id: "j1",
    title: "Доцент кафедры программной инженерии",
    department: "Факультет Информационных Технологий",
    staffCategory: "ППС (Профессорско-преподавательский состав)",
    academicDegree: "Кандидат наук / PhD",
    status: "Открыта",
    createdAt: "2026-05-12",
    location: "Главный корпус / Аудитория 402",
    employmentType: "Полная ставка (1.0)",
    description:
      "Ведение лекционных и практических занятий по дисциплинам алгоритмов и архитектуры ПО. Руководство дипломными проектами, участие в научно-исследовательской работе кафедры.",
    stages: DEFAULT_STAGES,
    salaryMin: 400000,
    salaryMax: 650000,
    currency: "KZT",
    workMode: "Офис (в университете)",
    experienceLevel: "3–6 лет",
    requiredSkills: ["Преподавание", "Алгоритмы", "Научные публикации", "React/Node"],
    openingsCount: 2,
    priority: "Высокий",
    recruiter: "Алия Р.",
    closingDate: "2026-08-15",
  },
  {
    id: "j2",
    title: "Инженер-электроник учебной лаборатории",
    department: "Департамент инфраструктуры",
    staffCategory: "Учебно-вспомогательный персонал (УВП)",
    academicDegree: "Не требуется",
    status: "Открыта",
    createdAt: "2026-05-20",
    location: "Корпус «Энергетик»",
    employmentType: "0.5 ставки",
    description:
      "Обслуживание и техническая поддержка оборудования в компьютерных классах и лабораториях микроконтроллеров. Подготовка рабочих мест к практическим занятиям студентов.",
    stages: DEFAULT_STAGES,
    salaryMin: 180000,
    salaryMax: 250000,
    currency: "KZT",
    workMode: "Офис (в университете)",
    experienceLevel: "1–3 года",
    requiredSkills: ["Пайка", "Диагностика ПК", "Сетевое оборудование"],
    openingsCount: 1,
    priority: "Средний",
    recruiter: "Данияр С.",
    closingDate: "2026-07-31",
  },
  {
    id: "j3",
    title: "HR Business Partner",
    department: "HR",
    status: "Закрыта",
    createdAt: "2026-03-10",
    location: "Астана",
    employmentType: "Полная занятость",
    description: "HRBP для поддержки инженерных команд. Позиция закрыта в июне.",
    stages: DEFAULT_STAGES,
    salaryMin: 2800000,
    salaryMax: 3600000,
    currency: "KZT",
    workMode: "Гибрид",
    experienceLevel: "1–3 года",
    requiredSkills: ["HR Strategy", "People Operations"],
    openingsCount: 1,
    priority: "Средний",
    recruiter: "Светлана К.",
    closingDate: "2026-06-30",
  },
  {
    id: "j4",
    title: "Sales Manager",
    department: "Sales",
    status: "Открыта",
    createdAt: "2026-06-15",
    location: "Алматы",
    employmentType: "Полная занятость",
    description: "Менеджер по продажам корпоративным клиентам. Опыл в B2B SaaS приветствуется.",
    stages: DEFAULT_STAGES,
    salaryMin: 3200000,
    salaryMax: 4600000,
    currency: "KZT",
    workMode: "Гибрид",
    experienceLevel: "1–3 года",
    requiredSkills: ["B2B Sales", "CRM", "Negotiation"],
    openingsCount: 3,
    priority: "Высокий",
    recruiter: "Бекжан М.",
    closingDate: "2026-08-10",
  },
];

export async function getJobs(): Promise<Job[]> {
  return initialJobs;
}