import { Job, DEFAULT_STAGES } from "./types";

export const initialJobs: Job[] = [
  {
    id: "j1",
    title: "Senior Frontend Developer",
    department: "Engineering",
    status: "Открыта",
    createdAt: "2026-05-12",
    location: "Алматы / Удалённо",
    employmentType: "Полная занятость",
    description:
      "Ищем сильного фронтенд-разработчика для развития продуктовой платформы. React, TypeScript, опыт с дизайн-системами будет плюсом. Команда — 6 инженеров, еженедельные релизы.",
    stages: DEFAULT_STAGES,
    salaryMin: 4000000,
    salaryMax: 6000000,
    currency: "KZT",
    workMode: "Гибрид",
    experienceLevel: "Senior",
    requiredSkills: ["React", "TypeScript", "Design Systems"],
    openingsCount: 1,
    priority: "Высокий",
    recruiter: "Алия Р.",
    closingDate: "2026-08-15",
  },
  {
    id: "j2",
    title: "Product Manager",
    department: "Product",
    status: "Открыта",
    createdAt: "2026-05-20",
    location: "Астана",
    employmentType: "Полная занятость",
    description:
      "Продуктовый менеджер для B2B-направления. Нужен опыт работы с discovery-исследованиями и метриками активации.",
    stages: DEFAULT_STAGES,
    salaryMin: 3000000,
    salaryMax: 4800000,
    currency: "KZT",
    workMode: "Удалённо",
    experienceLevel: "Middle",
    requiredSkills: ["Product Strategy", "Analytics", "Roadmapping"],
    openingsCount: 2,
    priority: "Средний",
    recruiter: "Данияр С.",
    closingDate: "2026-07-31",
  },
  {
    id: "j3",
    title: "UX/UI дизайнер",
    department: "Design",
    status: "На паузе",
    createdAt: "2026-04-02",
    location: "Удалённо",
    employmentType: "Полная занятость",
    description: "Дизайнер в продуктовую команду. Портфолио с кейсами по мобильным приложениям обязательно.",
    stages: DEFAULT_STAGES,
    salaryMin: 2600000,
    salaryMax: 3800000,
    currency: "KZT",
    workMode: "Удалённо",
    experienceLevel: "Middle",
    requiredSkills: ["Figma", "UI Systems", "User Research"],
    openingsCount: 1,
    priority: "Низкий",
    recruiter: "Марина П.",
    closingDate: "2026-08-01",
  },
  {
    id: "j4",
    title: "Backend Engineer (Go)",
    department: "Engineering",
    status: "Открыта",
    createdAt: "2026-06-01",
    location: "Алматы",
    employmentType: "Полная занятость",
    description: "Backend-разработчик на Go для платёжного сервиса. Высокие нагрузки, микросервисы, Kafka.",
    stages: DEFAULT_STAGES,
    salaryMin: 5000000,
    salaryMax: 7200000,
    currency: "KZT",
    workMode: "Офис",
    experienceLevel: "Senior",
    requiredSkills: ["Go", "Kafka", "Microservices"],
    openingsCount: 1,
    priority: "Высокий",
    recruiter: "Елена Т.",
    closingDate: "2026-08-20",
  },
  {
    id: "j5",
    title: "HR Business Partner",
    department: "HR",
    status: "Закрыта",
    createdAt: "2026-03-10",
    location: "Астана",
    employmentType: "Полная занятость",
    description: "HRBP для поддержки инженерных команд. Позиция закрыта в июне.",
    stages: DEFAULT_STAGES,
    salaryMin: 2800000,
    salaryMax: 3600000,
    currency: "KZT",
    workMode: "Гибрид",
    experienceLevel: "Middle",
    requiredSkills: ["HR Strategy", "People Operations"],
    openingsCount: 1,
    priority: "Средний",
    recruiter: "Светлана К.",
    closingDate: "2026-06-30",
  },
  {
    id: "j6",
    title: "Sales Manager",
    department: "Sales",
    status: "Открыта",
    createdAt: "2026-06-15",
    location: "Алматы",
    employmentType: "Полная занятость",
    description: "Менеджер по продажам корпоративным клиентам. Опыл в B2B SaaS приветствуется.",
    stages: DEFAULT_STAGES,
    salaryMin: 3200000,
    salaryMax: 4600000,
    currency: "KZT",
    workMode: "Гибрид",
    experienceLevel: "Middle",
    requiredSkills: ["B2B Sales", "CRM", "Negotiation"],
    openingsCount: 3,
    priority: "Высокий",
    recruiter: "Бекжан М.",
    closingDate: "2026-08-10",
  },
];

export async function getJobs(): Promise<Job[]> {
  return initialJobs;
}
