import { Candidate } from "./types";

const makeCandidate = (overrides: Partial<Candidate> & { id: string; name: string; jobId: string; stage: Candidate["stage"]; source: string; appliedDate: string; email: string; phone: string; location: string; skills: string[]; rating: number; resumeFileName: string; history: { date: string; action: string }[] }): Candidate => ({
  enterprise_id: "550e8400-e29b-41d4-a716-446655440000",
  user_id: null,
  status: "unassigned",
  assigned_vacancy_id: null,
  questionnaire: {
    surname: overrides.name.split(" ")[0] ?? overrides.name,
    first_name: overrides.name.split(" ")[1] ?? overrides.name,
    patronymic: "",
    gender: "не указан",
    birth_date: "",
    birth_place: "",
    nationality: "",
    citizenship: "",
    education_level: "",
    education: [],
    languages: "",
    academic_degree: "",
    scientific_works: [],
  },
  ai_score: null,
  ai_rankings: [],
  created_at: overrides.appliedDate,
  updated_at: overrides.appliedDate,
  ...overrides,
});

export const initialCandidates: Candidate[] = [
  makeCandidate({
    id: "c1",
    name: "Александр Ким",
    jobId: "j1",
    stage: "Интервью",
    source: "LinkedIn",
    appliedDate: "2026-06-02",
    email: "a.kim@mail.com",
    phone: "+7 701 111 2233",
    location: "Алматы",
    skills: ["React", "TypeScript", "GraphQL"],
    rating: 4,
    resumeFileName: "Kim_A_CV.pdf",
    history: [
      { date: "2026-06-02", action: "Отклик на вакансию" },
      { date: "2026-06-05", action: "Пройден скрининг-звонок" },
      { date: "2026-06-20", action: "Назначено техническое интервью" },
    ],
    questionnaire: {
      surname: "Ким",
      first_name: "Александр",
      patronymic: "",
      gender: "мужской",
      birth_date: "1992-04-18",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ им. аль-Фараби", year_from: "2010", year_to: "2015", dropped_at_year: null, specialty: "Информационные системы", diploma: "Диплом бакалавра № 12345" }],
      languages: "казахский (родной), русский (свободно), английский (B2)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 8.4,
    ai_rankings: [{ vacancy_id: "j1", vacancy_title: "Frontend Developer", score: 8.4 }],
  }),
  makeCandidate({
    id: "c2",
    name: "Дана Ахметова",
    jobId: "j1",
    stage: "Скрининг",
    source: "Реферал",
    appliedDate: "2026-06-10",
    email: "dana.a@mail.com",
    phone: "+7 701 222 3344",
    location: "Алматы",
    skills: ["React", "Next.js", "CSS"],
    rating: 5,
    resumeFileName: "Akhmetova_CV.pdf",
    history: [
      { date: "2026-06-10", action: "Рекомендована сотрудником" },
      { date: "2026-06-11", action: "Резюме на рассмотрении" },
    ],
    questionnaire: {
      surname: "Ахметова",
      first_name: "Дана",
      patronymic: "",
      gender: "женский",
      birth_date: "1994-09-22",
      birth_place: "г. Астана, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "Назарбаев Университет", year_from: "2012", year_to: "2016", dropped_at_year: null, specialty: "Менеджмент", diploma: "Бакалавр" }],
      languages: "русский (свободно), английский (B2)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 7.8,
    ai_rankings: [{ vacancy_id: "j1", vacancy_title: "Frontend Developer", score: 7.8 }],
  }),
  makeCandidate({
    id: "c3",
    name: "Тимур Сериков",
    jobId: "j1",
    stage: "Отклик",
    source: "HH.ru",
    appliedDate: "2026-06-25",
    email: "t.serikov@mail.com",
    phone: "+7 701 333 4455",
    location: "Шымкент",
    skills: ["Vue", "JavaScript"],
    rating: 3,
    resumeFileName: "Serikov_CV.pdf",
    history: [{ date: "2026-06-25", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Сериков",
      first_name: "Тимур",
      patronymic: "",
      gender: "мужской",
      birth_date: "1991-12-05",
      birth_place: "г. Шымкент, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "среднее специальное",
      education: [{ institution: "Колледж информационных технологий", year_from: "2008", year_to: "2012", dropped_at_year: null, specialty: "Программирование", diploma: "Техник" }],
      languages: "русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 6.1,
    ai_rankings: [{ vacancy_id: "j1", vacancy_title: "Frontend Developer", score: 6.1 }],
  }),
  makeCandidate({
    id: "c4",
    name: "Мадина Оспанова",
    jobId: "j2",
    stage: "Оффер",
    source: "Карьерный сайт",
    appliedDate: "2026-05-25",
    email: "m.ospanova@mail.com",
    phone: "+7 701 444 5566",
    location: "Астана",
    skills: ["Product Discovery", "SQL", "Figma"],
    rating: 5,
    resumeFileName: "Ospanova_CV.pdf",
    history: [
      { date: "2026-05-25", action: "Отклик на вакансию" },
      { date: "2026-06-01", action: "Скрининг пройден" },
      { date: "2026-06-15", action: "Финальное интервью" },
      { date: "2026-06-28", action: "Отправлен оффер" },
    ],
    questionnaire: {
      surname: "Оспанова",
      first_name: "Мадина",
      patronymic: "",
      gender: "женский",
      birth_date: "1990-02-14",
      birth_place: "г. Астана, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ им. аль-Фараби", year_from: "2008", year_to: "2013", dropped_at_year: null, specialty: "Психология", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 9.2,
    ai_rankings: [{ vacancy_id: "j2", vacancy_title: "Product Designer", score: 9.2 }],
  }),
  makeCandidate({
    id: "c5",
    name: "Ержан Абаев",
    jobId: "j2",
    stage: "Интервью",
    source: "LinkedIn",
    appliedDate: "2026-06-01",
    email: "e.abaev@mail.com",
    phone: "+7 701 555 6677",
    location: "Астана",
    skills: ["Аналитика", "A/B тесты"],
    rating: 4,
    resumeFileName: "Abaev_CV.pdf",
    history: [{ date: "2026-06-01", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Абаев",
      first_name: "Ержан",
      patronymic: "",
      gender: "мужской",
      birth_date: "1993-07-01",
      birth_place: "г. Астана, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ им. аль-Фараби", year_from: "2011", year_to: "2015", dropped_at_year: null, specialty: "Экономика", diploma: "Бакалавр" }],
      languages: "русский (свободно), английский (B2)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 7.2,
    ai_rankings: [{ vacancy_id: "j2", vacancy_title: "Product Designer", score: 7.2 }],
  }),
  makeCandidate({
    id: "c6",
    name: "Сауле Жумабекова",
    jobId: "j3",
    stage: "Скрининг",
    source: "Агентство",
    appliedDate: "2026-04-10",
    email: "s.zhuma@mail.com",
    phone: "+7 701 666 7788",
    location: "Удалённо",
    skills: ["Figma", "UX Research"],
    rating: 4,
    resumeFileName: "Zhumabekova_CV.pdf",
    history: [{ date: "2026-04-10", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Жумабекова",
      first_name: "Сауле",
      patronymic: "",
      gender: "женский",
      birth_date: "1995-03-12",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазГЮУ", year_from: "2013", year_to: "2018", dropped_at_year: null, specialty: "Дизайн", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 8.0,
    ai_rankings: [{ vacancy_id: "j3", vacancy_title: "Backend Developer", score: 8.0 }],
  }),
  makeCandidate({
    id: "c7",
    name: "Артём Волков",
    jobId: "j4",
    stage: "Интервью",
    source: "HH.ru",
    appliedDate: "2026-06-05",
    email: "a.volkov@mail.com",
    phone: "+7 701 777 8899",
    location: "Алматы",
    skills: ["Go", "PostgreSQL", "Kafka"],
    rating: 5,
    resumeFileName: "Volkov_CV.pdf",
    history: [
      { date: "2026-06-05", action: "Отклик на вакансию" },
      { date: "2026-06-18", action: "Тестовое задание выполнено" },
    ],
    questionnaire: {
      surname: "Волков",
      first_name: "Артём",
      patronymic: "",
      gender: "мужской",
      birth_date: "1989-11-10",
      birth_place: "г. Алматы, Казахстан",
      nationality: "русский",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ им. аль-Фараби", year_from: "2007", year_to: "2012", dropped_at_year: null, specialty: "Информатика", diploma: "Магистр" }],
      languages: "русский (родной), английский (C1)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 8.7,
    ai_rankings: [{ vacancy_id: "j4", vacancy_title: "Backend Developer", score: 8.7 }],
  }),
  makeCandidate({
    id: "c8",
    name: "Нурлан Байтасов",
    jobId: "j4",
    stage: "Скрининг",
    source: "Реферал",
    appliedDate: "2026-06-20",
    email: "n.baitasov@mail.com",
    phone: "+7 701 888 9900",
    location: "Алматы",
    skills: ["Go", "Docker"],
    rating: 3,
    resumeFileName: "Baitasov_CV.pdf",
    history: [{ date: "2026-06-20", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Байтасов",
      first_name: "Нурлан",
      patronymic: "",
      gender: "мужской",
      birth_date: "1996-05-03",
      birth_place: "г. Караганда, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "Карагандинский университет", year_from: "2014", year_to: "2018", dropped_at_year: null, specialty: "ИТ", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 6.4,
    ai_rankings: [{ vacancy_id: "j4", vacancy_title: "Backend Developer", score: 6.4 }],
  }),
  makeCandidate({
    id: "c9",
    name: "Айгерим Смагулова",
    jobId: "j4",
    stage: "Отказ",
    source: "LinkedIn",
    appliedDate: "2026-05-15",
    email: "a.smagulova@mail.com",
    phone: "+7 701 999 0011",
    location: "Караганда",
    skills: ["Java"],
    rating: 2,
    resumeFileName: "Smagulova_CV.pdf",
    history: [
      { date: "2026-05-15", action: "Отклик на вакансию" },
      { date: "2026-05-22", action: "Отказ после скрининга" },
    ],
    questionnaire: {
      surname: "Смагулова",
      first_name: "Айгерим",
      patronymic: "",
      gender: "женский",
      birth_date: "1998-08-30",
      birth_place: "г. Караганда, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "Карагандинский университет", year_from: "2016", year_to: "2020", dropped_at_year: null, specialty: "Программирование", diploma: "Бакалавр" }],
      languages: "русский (свободно), английский (A2)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 5.6,
    ai_rankings: [{ vacancy_id: "j4", vacancy_title: "Backend Developer", score: 5.6 }],
  }),
  makeCandidate({
    id: "c10",
    name: "Бекзат Нуртаев",
    jobId: "j6",
    stage: "Отклик",
    source: "Карьерный сайт",
    appliedDate: "2026-06-28",
    email: "b.nurtaev@mail.com",
    phone: "+7 701 000 1122",
    location: "Алматы",
    skills: ["B2B продажи", "CRM"],
    rating: 3,
    resumeFileName: "Nurtaev_CV.pdf",
    history: [{ date: "2026-06-28", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Нуртаев",
      first_name: "Бекзат",
      patronymic: "",
      gender: "мужской",
      birth_date: "1991-01-15",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ", year_from: "2009", year_to: "2014", dropped_at_year: null, specialty: "Маркетинг", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 6.9,
    ai_rankings: [{ vacancy_id: "j6", vacancy_title: "Sales Manager", score: 6.9 }],
  }),
  makeCandidate({
    id: "c11",
    name: "Айнур Тлеубаева",
    jobId: "j5",
    stage: "Нанят",
    source: "Реферал",
    appliedDate: "2026-03-12",
    email: "a.tleubaeva@mail.com",
    phone: "+7 701 123 4567",
    location: "Астана",
    skills: ["HR BP", "Employee Relations"],
    rating: 5,
    resumeFileName: "Tleubaeva_CV.pdf",
    history: [
      { date: "2026-03-12", action: "Отклик на вакансию" },
      { date: "2026-03-25", action: "Финальное интервью" },
      { date: "2026-04-02", action: "Оффер принят" },
    ],
    questionnaire: {
      surname: "Тлеубаева",
      first_name: "Айнур",
      patronymic: "",
      gender: "женский",
      birth_date: "1990-10-18",
      birth_place: "г. Астана, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "Евразийский национальный университет", year_from: "2008", year_to: "2013", dropped_at_year: null, specialty: "HR", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 9.4,
    ai_rankings: [{ vacancy_id: "j5", vacancy_title: "HRBP", score: 9.4 }],
  }),
  makeCandidate({
    id: "c12",
    name: "Данияр Ислямов",
    jobId: "j1",
    stage: "Отказ",
    source: "HH.ru",
    appliedDate: "2026-05-28",
    email: "d.islyamov@mail.com",
    phone: "+7 701 234 5678",
    location: "Алматы",
    skills: ["Angular"],
    rating: 2,
    resumeFileName: "Islyamov_CV.pdf",
    history: [{ date: "2026-05-28", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Ислямов",
      first_name: "Данияр",
      patronymic: "",
      gender: "мужской",
      birth_date: "1992-08-20",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "МУИТ", year_from: "2010", year_to: "2015", dropped_at_year: null, specialty: "Информационные технологии", diploma: "Бакалавр" }],
      languages: "русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 5.2,
    ai_rankings: [{ vacancy_id: "j1", vacancy_title: "Frontend Developer", score: 5.2 }],
  }),
  makeCandidate({
    id: "c13",
    name: "Жанна Рахимова",
    jobId: "j2",
    stage: "Скрининг",
    source: "LinkedIn",
    appliedDate: "2026-06-18",
    email: "zh.rakhimova@mail.com",
    phone: "+7 701 345 6789",
    location: "Астана",
    skills: ["Roadmapping", "Jira"],
    rating: 4,
    resumeFileName: "Rakhimova_CV.pdf",
    history: [{ date: "2026-06-18", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Рахимова",
      first_name: "Жанна",
      patronymic: "",
      gender: "женский",
      birth_date: "1994-06-14",
      birth_place: "г. Астана, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "Назарбаев Университет", year_from: "2012", year_to: "2016", dropped_at_year: null, specialty: "Product Management", diploma: "Бакалавр" }],
      languages: "русский (свободно), английский (B2)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 7.9,
    ai_rankings: [{ vacancy_id: "j2", vacancy_title: "Product Designer", score: 7.9 }],
  }),
  makeCandidate({
    id: "c14",
    name: "Олжас Кенжебаев",
    jobId: "j3",
    stage: "Отклик",
    source: "Карьерный сайт",
    appliedDate: "2026-06-27",
    email: "o.kenzhebaev@mail.com",
    phone: "+7 701 456 7890",
    location: "Алматы",
    skills: ["Figma", "Illustrator"],
    rating: 3,
    resumeFileName: "Kenzhebaev_CV.pdf",
    history: [{ date: "2026-06-27", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Кенжебаев",
      first_name: "Олжас",
      patronymic: "",
      gender: "мужской",
      birth_date: "1993-09-09",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазГЮУ", year_from: "2011", year_to: "2015", dropped_at_year: null, specialty: "Дизайн", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 6.7,
    ai_rankings: [{ vacancy_id: "j3", vacancy_title: "Backend Developer", score: 6.7 }],
  }),
  makeCandidate({
    id: "c15",
    name: "Гульнара Есенова",
    jobId: "j6",
    stage: "Интервью",
    source: "Агентство",
    appliedDate: "2026-06-08",
    email: "g.esenova@mail.com",
    phone: "+7 701 567 8901",
    location: "Алматы",
    skills: ["B2B продажи", "Переговоры"],
    rating: 4,
    resumeFileName: "Esenova_CV.pdf",
    history: [{ date: "2026-06-08", action: "Отклик на вакансию" }],
    questionnaire: {
      surname: "Есенова",
      first_name: "Гульнара",
      patronymic: "",
      gender: "женский",
      birth_date: "1988-04-20",
      birth_place: "г. Алматы, Казахстан",
      nationality: "казах",
      citizenship: "Казахстан",
      education_level: "высшее",
      education: [{ institution: "КазНУ", year_from: "2006", year_to: "2011", dropped_at_year: null, specialty: "Маркетинг", diploma: "Бакалавр" }],
      languages: "казахский (родной), русский (свободно)",
      academic_degree: "",
      scientific_works: [],
    },
    ai_score: 8.1,
    ai_rankings: [{ vacancy_id: "j6", vacancy_title: "Sales Manager", score: 8.1 }],
  }),
];

export async function getCandidates(): Promise<Candidate[]> {
  return initialCandidates;
}

export async function getCandidateById(id: string): Promise<Candidate | null> {
  const candidates = await getCandidates();
  return candidates.find((c) => c.id === id) ?? null;
}