import { Interview } from "./types";

export const interviews: Interview[] = [
  {
    id: "i1",
    candidateId: "c1",
    day: 0,
    startHour: 11,
    duration: 1,
    interviewer: "Анна Петрова",
    type: "Видео",
  },
  {
    id: "i2",
    candidateId: "c5",
    day: 0,
    startHour: 14,
    duration: 1,
    interviewer: "Мария Ким",
    type: "Видео",
  },
  {
    id: "i3",
    candidateId: "c7",
    day: 1,
    startHour: 10,
    duration: 1.5,
    interviewer: "Игорь Соколов",
    type: "Очно",
  },
  {
    id: "i4",
    candidateId: "c4",
    day: 1,
    startHour: 16,
    duration: 1,
    interviewer: "Дмитрий Волков",
    type: "Видео",
  },
  {
    id: "i5",
    candidateId: "c2",
    day: 2,
    startHour: 12,
    duration: 0.5,
    interviewer: "Анна Петрова",
    type: "Звонок",
  },
  {
    id: "i6",
    candidateId: "c15",
    day: 2,
    startHour: 15,
    duration: 1,
    interviewer: "Игорь Соколов",
    type: "Видео",
  },
  {
    id: "i7",
    candidateId: "c8",
    day: 3,
    startHour: 9,
    duration: 1,
    interviewer: "Анна Петрова",
    type: "Видео",
  },
  {
    id: "i8",
    candidateId: "c13",
    day: 4,
    startHour: 13,
    duration: 1,
    interviewer: "Мария Ким",
    type: "Очно",
  },
];
