import { DashboardPageView } from "@/views/dashboard";
import type { DashboardPageViewProps } from "@/views/dashboard/ui/DashboardView";

export default async function DashboardPage() {
  const data = {
    activeJobsCount: 12,
    inProgressCandidates: 48,
    todaysInterviewsCount: 7,
    pipelineCounts: [
      { stage: "Скрининг", count: 18 },
      { stage: "Интервью", count: 12 },
      { stage: "Оффер", count: 9 },
      { stage: "Нанят", count: 5 },
    ],
    maxPipeline: 20,
    todaysInterviews: [
      {
        id: "1",
        candidateId: "c1",
        type: "Очно",
        startHour: 10,
        duration: 1,
        interviewer: "Анна Петрова",
        day: 0,
      },
      {
        id: "2",
        candidateId: "c2",
        type: "Звонок",
        startHour: 11,
        duration: 0.5,
        interviewer: "Игорь Соколов",
        day: 0,
      },
      {
        id: "3",
        candidateId: "c3",
        type: "Видео",
        startHour: 13,
        duration: 1,
        interviewer: "Мария Ким",
        day: 0,
      },
    ],
    candidateById: {
      c1: {
        id: "c1",
        name: "Алексей Иванов",
        jobId: "j1",
        stage: "Интервью",
        source: "HeadHunter",
        appliedDate: "2025-01-10",
        email: "alexey.ivanov@example.com",
        phone: "+7 900 000-00-01",
        location: "Москва",
        skills: ["React", "TypeScript"],
        rating: 4,
        resumeFileName: "ivanov_resume.pdf",
        history: [],
      },
      c2: {
        id: "c2",
        name: "Марина Кузнецова",
        jobId: "j2",
        stage: "Интервью",
        source: "LinkedIn",
        appliedDate: "2025-01-12",
        email: "marina.kuznetsova@example.com",
        phone: "+7 900 000-00-02",
        location: "Санкт-Петербург",
        skills: ["Figma", "UX Research"],
        rating: 5,
        resumeFileName: "kuznetsova_resume.pdf",
        history: [],
      },
      c3: {
        id: "c3",
        name: "Дмитрий Соловьёв",
        jobId: "j3",
        stage: "Интервью",
        source: "Рекомендация",
        appliedDate: "2025-01-14",
        email: "dmitry.solovyov@example.com",
        phone: "+7 900 000-00-03",
        location: "Москва",
        skills: ["Node.js", "PostgreSQL"],
        rating: 4,
        resumeFileName: "solovyov_resume.pdf",
        history: [],
      },
    },
    jobById: {
      j1: {
        id: "j1",
        title: "Frontend Developer",
        department: "Разработка",
        status: "Открыта",
        createdAt: "2025-01-15",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
      j2: {
        id: "j2",
        title: "Product Designer",
        department: "Дизайн",
        status: "Открыта",
        createdAt: "2025-01-20",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
      j3: {
        id: "j3",
        title: "Backend Developer",
        department: "Разработка",
        status: "Открыта",
        createdAt: "2025-02-01",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
    },
  } satisfies DashboardPageViewProps;

  return <DashboardPageView {...data} />;
}
