import { DashboardPageView } from "@/views/dashboard";
import type { DashboardPageViewProps } from "@/views/dashboard/ui/DashboardView";

export default async function DashboardPage() {
  const data = {
    activeJobsCount: 12,
    inProgressCandidates: 48,
    todaysInterviewsCount: 7,
    pipelineCounts: [
      { stage: "Скрининг", count: 18 },
      { stage: "Интервью", count: 12 },
      { stage: "Оффер", count: 9 },
      { stage: "Нанят", count: 5 },
    ],
    maxPipeline: 20,
    todaysInterviews: [
      {
        id: "1",
        candidateId: "c1",
        type: "Очно",
        startHour: 10,
        duration: 1,
        interviewer: "Анна Петрова",
        day: 0,
      },
      {
        id: "2",
        candidateId: "c2",
        type: "Звонок",
        startHour: 11,
        duration: 0.5,
        interviewer: "Игорь Соколов",
        day: 0,
      },
      {
        id: "3",
        candidateId: "c3",
        type: "Видео",
        startHour: 13,
        duration: 1,
        interviewer: "Мария Ким",
        day: 0,
      },
    ],
    candidateById: {
      c1: {
        id: "c1",
        enterprise_id: "550e8400-e29b-41d4-a716-446655440000",
        user_id: null,
        status: "assigned",
        assigned_vacancy_id: "j1",
        questionnaire: {
          surname: "Иванов",
          first_name: "Алексей",
          patronymic: "",
          gender: "мужской",
          birth_date: "1995-03-15",
          birth_place: "Москва",
          nationality: "русский",
          citizenship: "Россия",
          education_level: "высшее",
          education: [],
          languages: "русский (родной), английский (B2)",
          academic_degree: "",
          scientific_works: [],
        },
        ai_score: 7.4,
        ai_rankings: [{ vacancy_id: "j1", vacancy_title: "Frontend Developer", score: 7.4 }],
        created_at: "2025-01-10T00:00:00.000Z",
        updated_at: "2025-01-10T00:00:00.000Z",
        name: "Алексей Иванов",
        jobId: "j1",
        stage: "Интервью",
        source: "HeadHunter",
        appliedDate: "2025-01-10",
        email: "alexey.ivanov@example.com",
        phone: "+7 900 000-00-01",
        location: "Москва",
        skills: ["React", "TypeScript"],
        rating: 4,
        resumeFileName: "ivanov_resume.pdf",
        history: [],
      },
      c2: {
        id: "c2",
        enterprise_id: "550e8400-e29b-41d4-a716-446655440000",
        user_id: null,
        status: "assigned",
        assigned_vacancy_id: "j2",
        questionnaire: {
          surname: "Кузнецова",
          first_name: "Марина",
          patronymic: "",
          gender: "женский",
          birth_date: "1994-09-30",
          birth_place: "Санкт-Петербург",
          nationality: "русская",
          citizenship: "Россия",
          education_level: "высшее",
          education: [],
          languages: "русский (родной), английский (B2)",
          academic_degree: "",
          scientific_works: [],
        },
        ai_score: 8.1,
        ai_rankings: [{ vacancy_id: "j2", vacancy_title: "Product Designer", score: 8.1 }],
        created_at: "2025-01-12T00:00:00.000Z",
        updated_at: "2025-01-12T00:00:00.000Z",
        name: "Марина Кузнецова",
        jobId: "j2",
        stage: "Интервью",
        source: "LinkedIn",
        appliedDate: "2025-01-12",
        email: "marina.kuznetsova@example.com",
        phone: "+7 900 000-00-02",
        location: "Санкт-Петербург",
        skills: ["Figma", "UX Research"],
        rating: 5,
        resumeFileName: "kuznetsova_resume.pdf",
        history: [],
      },
      c3: {
        id: "c3",
        enterprise_id: "550e8400-e29b-41d4-a716-446655440000",
        user_id: null,
        status: "assigned",
        assigned_vacancy_id: "j3",
        questionnaire: {
          surname: "Соловьёв",
          first_name: "Дмитрий",
          patronymic: "",
          gender: "мужской",
          birth_date: "1993-06-07",
          birth_place: "Москва",
          nationality: "русский",
          citizenship: "Россия",
          education_level: "высшее",
          education: [],
          languages: "русский (родной), английский (B1)",
          academic_degree: "",
          scientific_works: [],
        },
        ai_score: 7.1,
        ai_rankings: [{ vacancy_id: "j3", vacancy_title: "Backend Developer", score: 7.1 }],
        created_at: "2025-01-14T00:00:00.000Z",
        updated_at: "2025-01-14T00:00:00.000Z",
        name: "Дмитрий Соловьёв",
        jobId: "j3",
        stage: "Интервью",
        source: "Рекомендация",
        appliedDate: "2025-01-14",
        email: "dmitry.solovyov@example.com",
        phone: "+7 900 000-00-03",
        location: "Москва",
        skills: ["Node.js", "PostgreSQL"],
        rating: 4,
        resumeFileName: "solovyov_resume.pdf",
        history: [],
      },
    },
    jobById: {
      j1: {
        id: "j1",
        title: "Frontend Developer",
        department: "Разработка",
        status: "Открыта",
        createdAt: "2025-01-15",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
      j2: {
        id: "j2",
        title: "Product Designer",
        department: "Дизайн",
        status: "Открыта",
        createdAt: "2025-01-20",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
      j3: {
        id: "j3",
        title: "Backend Developer",
        department: "Разработка",
        status: "Открыта",
        createdAt: "2025-02-01",
        location: "Москва",
        employmentType: "Полная занятость",
        description: "",
        stages: ["Отклик", "Скрининг", "Интервью", "Оффер", "Нанят"],
      },
    },
  } satisfies DashboardPageViewProps;

  return <DashboardPageView {...data} />;
}
